Statements
    Assign
        x
        0
    If-Else
        =
            x
            1
        Statements
            Assign
                x
                1
        Statements
            Assign
                x
                2
    Assign
        y
        0
    If
        AND
        Statements
            Assign
                x
                2
